spring:
  datasource:
    url: jdbc:h2:file:C:/temp/taco3
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /api

taco:
  orders:
    pageSize: 5

  discount:
    codes:
      abcdef: 10


---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN

